name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        . ~/.nvm/nvm.sh
        nvm install
        cd wrapper
        yarn install
        yarn build
        cd ..
        yarn install
        yarn build

    - name: Format
      run: yarn fmt-check
